[package]
name = "gltf-viewer"
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2024"

[dependencies]
nightshade = { version = "0.6.61", features = ["egui", "tracing"] }

[features]
openxr = ["nightshade/openxr"]
